### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by yw4c** [yw4c/orchestrator#1]
- [ ] reconnect to NATS server, while server restart 
- [ ] release throttling unfinished request element
- [ ] mq factory
- [ ] improve readme, framework tool usage, e.g. error handling
